defaults:
  - default
  - _self_

# Override from `default` config
id: MeentIndexEfield-v0
max_episode_steps: 1024

# Wrapper to be instantiated
wrapper:
  _target_: sheeprl.envs.metasurface.get_deflector_env
  id: ${env.id}
