experiment: UNet
device: cuda:0
################################################################################
seed : 7 # 42, 170
model: UNet
model_config:
  n_channels: 1

n_epochs: 101
# regularizer: True

loss: h1
loss_config:
  reductions: mean
eval_losses: [carsten_l2, carsten_h1]

optim: AdamW
optim_config:
  lr: 1e-3
  weight_decay: 1e-6

save_interval: 50

scheduler: OneCycleLR
scheduler_config:
  max_lr: 1e-2
  total_steps: 101
  base_momentum: 0.85
  max_momentum: 0.95

# 1100-70-4 1100-50-4 900-70-4 900-50-4
data: 1100-70-4
################################################################################
hydra:
  run:
    dir: ./runs/${experiment}-${seed}-${data}-${now:%m%d-%H%M%S}
